/* Build js/data.js from data/units/unit-*.json
   Usage: node build.js
   Validates each unit's shape, then embeds everything as window.VOCAB_DATA
   so the site works both on GitHub Pages and when opened as a local file. */
const fs = require("fs");
const path = require("path");

const UNITS_DIR = path.join(__dirname, "data", "units");
const OUT = path.join(__dirname, "js", "data.js");

const REQ_UNIT = ["id", "slug", "title_en", "title_vi", "emoji", "words"];
const REQ_WORD = ["word", "ipa", "pos", "vi", "example_en", "example_vi", "emoji"];

function fail(msg) { console.error("✗ " + msg); process.exitCode = 1; }

const files = fs.readdirSync(UNITS_DIR)
  .filter(f => /^unit-\d+\.json$/.test(f))
  .sort();

const units = [];
let totalWords = 0;
const seenIds = new Set();

for (const f of files) {
  const full = path.join(UNITS_DIR, f);
  let obj;
  try {
    obj = JSON.parse(fs.readFileSync(full, "utf8"));
  } catch (e) {
    fail(`${f}: invalid JSON — ${e.message}`);
    continue;
  }
  for (const k of REQ_UNIT) if (!(k in obj)) fail(`${f}: missing unit key "${k}"`);
  if (!Array.isArray(obj.words) || obj.words.length === 0) { fail(`${f}: no words`); continue; }
  if (seenIds.has(obj.id)) fail(`${f}: duplicate unit id ${obj.id}`);
  seenIds.add(obj.id);

  obj.words.forEach((w, i) => {
    for (const k of REQ_WORD) {
      if (!(k in w)) fail(`${f}: word #${i + 1} (${w.word || "?"}) missing "${k}"`);
    }
  });
  totalWords += obj.words.length;
  units.push(obj);
  console.log(`  ✓ ${f}: ${obj.words.length} words  (${obj.title_en})`);
}

units.sort((a, b) => a.id - b.id);

const payload = { generatedWords: totalWords, unitCount: units.length, units };
const banner =
  "/* AUTO-GENERATED by build.js — do not edit by hand.\n" +
  "   Source: data/units/unit-*.json\n" +
  `   ${units.length} units, ${totalWords} words. */\n`;

fs.writeFileSync(OUT, banner + "window.VOCAB_DATA = " + JSON.stringify(payload) + ";\n", "utf8");

console.log(`\n→ Wrote ${path.relative(__dirname, OUT)}  —  ${units.length} units, ${totalWords} words`);
if (process.exitCode) console.error("\nBuild finished WITH ERRORS (see above).");
else console.log("Build OK.");
