/* Build js/data.js from data/units/unit-*.json
   Usage: node build.js
   Validates each unit's shape, then embeds everything as window.VOCAB_DATA
   so the site works both on GitHub Pages and when opened as a local file. */
const fs = require("fs");
const path = require("path");

const UNITS_DIR = path.join(__dirname, "data", "units");
const OUT = path.join(__dirname, "js", "data.js");

const REQ_UNIT = ["id", "slug", "title_en", "title_vi", "emoji", "words"];
const REQ_WORD = ["word", "ipa", "pos", "vi", "example_en", "example_vi", "emoji"];

function fail(msg) { console.error("✗ " + msg); process.exitCode = 1; }

const files = fs.readdirSync(UNITS_DIR)
  .filter(f => /^unit-\d+\.json$/.test(f))
  .sort();

const REQ_PHRASE = ["en", "vi", "example_en", "example_vi"];

const units = [];
let totalWords = 0;
let totalPhrases = 0;
const seenIds = new Set();

for (const f of files) {
  const full = path.join(UNITS_DIR, f);
  let obj;
  try {
    obj = JSON.parse(fs.readFileSync(full, "utf8"));
  } catch (e) {
    fail(`${f}: invalid JSON — ${e.message}`);
    continue;
  }
  for (const k of REQ_UNIT) if (!(k in obj)) fail(`${f}: missing unit key "${k}"`);
  if (!Array.isArray(obj.words) || obj.words.length === 0) { fail(`${f}: no words`); continue; }
  if (seenIds.has(obj.id)) fail(`${f}: duplicate unit id ${obj.id}`);
  seenIds.add(obj.id);

  obj.words.forEach((w, i) => {
    for (const k of REQ_WORD) {
      if (!(k in w)) fail(`${f}: word #${i + 1} (${w.word || "?"}) missing "${k}"`);
    }
  });
  totalWords += obj.words.length;

  // Merge optional collocations/phrases from unit-XX.phrases.json (kept separate
  // so regenerating phrases never risks the core word data).
  const phrasesFile = full.replace(/\.json$/, ".phrases.json");
  obj.phrases = [];
  if (fs.existsSync(phrasesFile)) {
    try {
      const arr = JSON.parse(fs.readFileSync(phrasesFile, "utf8"));
      if (Array.isArray(arr)) {
        arr.forEach((p, i) => {
          for (const k of REQ_PHRASE) if (!(k in p)) fail(`${path.basename(phrasesFile)}: item #${i + 1} missing "${k}"`);
        });
        obj.phrases = arr;
        totalPhrases += arr.length;
      } else {
        fail(`${path.basename(phrasesFile)}: expected a JSON array`);
      }
    } catch (e) {
      fail(`${path.basename(phrasesFile)}: invalid JSON — ${e.message}`);
    }
  }

  units.push(obj);
  console.log(`  ✓ ${f}: ${obj.words.length} words, ${obj.phrases.length} phrases  (${obj.title_en})`);
}

units.sort((a, b) => a.id - b.id);

const payload = { generatedWords: totalWords, totalPhrases: totalPhrases, unitCount: units.length, units };
const banner =
  "/* AUTO-GENERATED by build.js — do not edit by hand.\n" +
  "   Source: data/units/unit-*.json (+ optional unit-*.phrases.json)\n" +
  `   ${units.length} units, ${totalWords} words, ${totalPhrases} phrases. */\n`;

fs.writeFileSync(OUT, banner + "window.VOCAB_DATA = " + JSON.stringify(payload) + ";\n", "utf8");

console.log(`\n→ Wrote ${path.relative(__dirname, OUT)}  —  ${units.length} units, ${totalWords} words, ${totalPhrases} phrases`);
if (process.exitCode) console.error("\nBuild finished WITH ERRORS (see above).");
else console.log("Build OK.");
